const express = require("express");
const jwt = require("jsonwebtoken");
const router = express.Router();
const db = require("../models");

// LOAD EVENTS HOSTED EVENTS WHERE HOSTID = USERID PASSED INTO HEADERS

// LOAD ATTENDING EVENTS WHERE USERID IS INCLUDED IN THE ATTENDEES ARRAY

// UPDATE TO ADD USER TO ATTENDEE ARRAY - REMOVE USERID OF LOGGED IN USER

// UPDATE TO REMOVE USER FROM ATTENDEE ARRAY - REMOVE USERID OF LOGGED IN USER

module.exports = router;